log:
  level: debug

listen: :443 #监听端口

#使用自签证书
tls:
  cert: /etc/hysteria/server.crt
  key: /etc/hysteria/server.key
  alpn: ["h3"]

# 2. 增加混淆配置 (Obfuscation)
obfs:
  type: salamander
  salamander: # 【必须增加这一行】
    password: "zx8257686@520" # 【缩进】密码要放在这里

auth:
  type: http
  http:
    url: http://127.0.0.1:8080/auth
    timeout: 5s

masquerade:
  type: proxy
  proxy:
    url: https://bing.com #伪装网址
    rewriteHost: true

# 流量统计 API 配置
trafficStats:
  listen: :8081 # 修改端口以避免与 Auth Server 冲突
  secret: zx8257686@520 # API 访问密钥
