listen: :443 #监听端口

#使用自签证书
tls:
  cert: /etc/hysteria/server.crt
  key: /etc/hysteria/server.key

auth:
  type: http
  http:
    url: http://auth-server:8080/auth
    timeout: 5s

# 流量统计 API 配置
trafficStats:
  listen: :8081 # 修改端口以避免与 Auth Server 冲突
  secret: zx8257686@520 # API 访问密钥
